// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvn2CokKJ9OomRBuiUyrGQluqxrH35zHc',
    appId: '1:329282500119:web:99eb4edd24a21b6e620e52',
    messagingSenderId: '329282500119',
    projectId: 'flutter-app-125fc',
    authDomain: 'flutter-app-125fc.firebaseapp.com',
    storageBucket: 'flutter-app-125fc.appspot.com',
    measurementId: 'G-8X42HNQGV9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNI-0Fj4KRG_TviOZ0UdU9_06LEwIwuEc',
    appId: '1:329282500119:android:814af5f8dea62006620e52',
    messagingSenderId: '329282500119',
    projectId: 'flutter-app-125fc',
    storageBucket: 'flutter-app-125fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnPJv8iaxJijKG6WhrE2ADq33J7BVoUt0',
    appId: '1:329282500119:ios:7bee2a481f3f8cec620e52',
    messagingSenderId: '329282500119',
    projectId: 'flutter-app-125fc',
    storageBucket: 'flutter-app-125fc.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnPJv8iaxJijKG6WhrE2ADq33J7BVoUt0',
    appId: '1:329282500119:ios:7bee2a481f3f8cec620e52',
    messagingSenderId: '329282500119',
    projectId: 'flutter-app-125fc',
    storageBucket: 'flutter-app-125fc.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvn2CokKJ9OomRBuiUyrGQluqxrH35zHc',
    appId: '1:329282500119:web:48fb3a2b8d879293620e52',
    messagingSenderId: '329282500119',
    projectId: 'flutter-app-125fc',
    authDomain: 'flutter-app-125fc.firebaseapp.com',
    storageBucket: 'flutter-app-125fc.appspot.com',
    measurementId: 'G-HSZ01N1JY6',
  );

}